### ISSUE TITLE
Type mismatch when defining kotlinVersion

### ISSUE THREAD

**Issue by Jpunt** [THEOplayer/react-native-theoplayer#156] opened 2023-07-12 12:42 UTC
Since we've explicitly defined `kotlinVersion` in our `build.gradle`, THEOplayer struggles to build with the following error:

```
'compileDebugJavaWithJavac' task (current target is 11) and 'compileDebugKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
e: /Users/jasper/code/my-demo-app/node_modules/react-native-theoplayer/android/src/main/java/com/theoplayer/presentation/PipUtils.kt: (75, 39): Type mismatch: inferred type is EventListener<PlayerEvent<*>>? but EventListener<in TypeVariable(T)!> was expected
e: /Users/jasper/code/my-demo-app/node_modules/react-native-theoplayer/android/src/main/java/com/theoplayer/presentation/PipUtils.kt: (78, 43): Type mismatch: inferred type is EventListener<GoogleImaAdEvent>? but EventListener<in TypeVariable(T)!> was expected
e: /Users/jasper/code/my-demo-app/node_modules/react-native-theoplayer/android/src/main/java/com/theoplayer/presentation/PipUtils.kt: (92, 42): Type mismatch: inferred type is EventListener<PlayerEvent<*>>? but EventListener<in TypeVariable(T)!> was expected
e: /Users/jasper/code/my-demo-app/node_modules/react-native-theoplayer/android/src/main/java/com/theoplayer/presentation/PipUtils.kt: (95, 46): Type mismatch: inferred type is EventListener<GoogleImaAdEvent>? but EventListener<in TypeVariable(T)!> was expected
```

I must say I'm not entirely confident about what causes this issue, but some remarks we've found while debugging this:
- Most libraries base their version of `org.jetbrains.kotlin:kotlin-gradle-plugin` on `kotlinVersion` defined in the root-project, while `react-native-theoplayer` has this hardcoded to `1.7.21`. Setting our `kotlinVersion` to the same version doesn't fix our issue, but it seems to be a good practice not to fixate this. Not sure why it is?
- We've tried different versions of Kotlin (`1.7.21`, `1.8.22` for example), but this all leads to the same error it seems.

<img width="1005" alt="Screenshot 2023-07-12 at 14 43 45" src="https://github.com/THEOplayer/react-native-theoplayer/assets/190501/25c124d5-5d05-4aa7-aafe-0b4a7d2b68a3">

**Comment by davidwinograd1** [comment] 2023-07-13 20:40
I am getting this issue, too!

**Comment by wlkodlak** [comment] 2023-07-17 09:39
I'm getting same issue. Quick workaround is forcing SDK version 5.5.0 using `THEOplayer_sdk` in `gradle.properties` (see https://github.com/THEOplayer/react-native-theoplayer/blob/develop/doc/creating-minimal-app.md#getting-started-on-android). Latest version 5.6.0 seems to be incompatible at the moment.

**Comment by davidwinograd1** [comment] 2023-07-17 16:16
This seems to have gotten rid of it -- thank you!

**Comment by Jpunt** [comment] 2023-07-18 11:15
This a great workaround indeed, thanks! I hope this will get fixed properly though 👍

**Comment by wvanhaevre** [comment] 2023-07-19 07:55
We will indeed have a look at this and share an update...

**Comment by wvanhaevre** [comment] 2023-07-19 08:34
We are currently looking into the issue and will provide a fix somewhere during the next week. For now the above suggested workaround to stick to 5.5 should indeed unblock further development.

**Comment by tvanlaerhoven** [comment] 2023-07-24 10:44
The cause of the issue is an upgrade of the native player's SDK Java version to 1.8, which breaks the Kotlin code in PipUtils that interacts with it.
The upcoming v2.10.0 that will be released shortly contains a fix.

**Closed** 2023-07-24 12:03 UTC
Labels: bug
